services:
        user.form.registration:
            class: UserBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: user_registration }
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
